Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,24 +25,33 @@ jobs:
             --reporters cli,allure \
             --reporter-allure-export allure-results || echo "Тесты провалены" > failed_tests.txt || true
 
+      - name: 🔍 Запуск API-тестов
+        run: |
+          newman run postman_collection_auth_fixed.json \
+            --environment postman_environment.json \
+            --reporters cli,allure \
+            --reporter-allure-export allure-results || echo "Тесты провалены" > failed_tests.txt || true
+
       - name: 📊 Генерация отчета Allure (всегда)
         if: always()
         run: |
           allure generate allure-results --clean -o allure-report || true
 
       - name: 📤 Загрузка отчета в GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./allure-report
-          publish_branch: gh-pages  # Указываем, куда пушить
+        if: always()
+        run: |
+          git checkout --orphan gh-pages
+          git --work-tree=allure-report add --all
+          git commit -m "Обновлен отчет"
+          git push origin HEAD:gh-pages --force || true
 
       - name: 📡 Отправка отчета в Telegram
+        if: always()
         run: |
           MESSAGE="✅ API-тесты успешно пройдены!"
           if [ -f failed_tests.txt ]; then MESSAGE="❌ API-тесты провалены!"; fi
-          MESSAGE="$MESSAGE%0A📊 Отчет: https://Farabi001.github.io/postman-api-tests/"
-
+          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/postman-api-tests/"
+          
           curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
-          -d "text=$MESSAGE"
+            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
+            -d "text=$MESSAGE"
